import random

SCREEN_WIDTH = 1401
SCREEN_HEIGHT = 788
WATER_HEIGHT = 387
LOW_HEIGHT= 650
BSHIP_SPEED = 1
C_SPEED = 2
D_SPEED = 3
TORPEDO_SPEED = 4
NUM_BB = 3
hvary= random.randint(WATER_HEIGHT, LOW_HEIGHT)